blank_issues_enabled: false
contact_links:
  - name: Share an event or talk you are doing
    url: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/23/create/514
    about: Share any events or talks you are doing and want us to promote via social and our events page
  - name: Submit an Open Mainframe Project blog post
    url: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/23/create/511
    about: Submit a blog post for the Open Mainframe Project blog
  - name: Sponsorship/support of your event
    url: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/23/create/500
    about: Request Open Mainframe Project to sponsor/support a member or other community event
  - name: Marketing Support
    url: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/23/create/511
    about: Submit a guest blog post for openmainframeproject.org and/or linux.com, video to upload to YouTube, host a webinar, or any other social media request.
  - name: Project Infrastructure Support
    url: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/group/6
    about: Request new or changes to mailing list, Slack channel, GitHub organization, 1Password vault, or other infrastructure
  - name: Transfer domain to Open Mainframe Project
    url: https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63
    about: For transfering a project-owned domain to the Open Mainframe Project
  - name: Open Mainframe Project Landscape entry requests
    url: https://github.com/openmainframeproject/omp-landscape/issues/new/choose
    about: Any requests for adding or updating Open Mainframe Project Landscape entries
  - name: Other Open Mainframe Project member support requests
    url: http://members.openmainframeproject.org/
    about: Member specific requests, including invoicing, contact management, and participation in member-exclusive groups
