contact_links:
  - name: Open Mainframe Project member support
    url: http://members.openmainframeproject.org/
    about: Member specific requests, including invoicing, contact management, and participation in member-exclusive groups
